// API metadata adapted from cc-switch (MIT), not executable upstream code.
// Source commit: da193d4f7a6ce3710623c312245c752376c0d036
// Full attribution and license: THIRD_PARTY_NOTICES.md.
// apiFormat wins over the Codex-facing wire_api; absent apiFormat uses the
// source generateThirdPartyConfig helper's Responses default.
export type CodexPresetRow = readonly [
  id: string, sourceName: string, apiFormat: 'openai_chat' | 'openai_responses',
  baseURL: string, modelExamples: readonly string[],
  category: 'cn_official' | 'aggregator' | 'third_party',
];
export const CC_SWITCH_CODEX_SOURCE = {
  commit: 'da193d4f7a6ce3710623c312245c752376c0d036',
  path: 'src/config/codexProviderPresets.ts',
  entries: 93,
  excluded: [
    { name: 'OpenAI Official', reason: 'Codex OAuth login, not an API Key preset' },
    { name: 'xAI (Grok) OAuth', reason: 'Managed OAuth account required; API Key variant is included' },
    { name: 'Azure OpenAI', reason: 'Resource placeholder and api-version query require additional adapter configuration' },
  ],
} as const;
export const CC_SWITCH_CODEX_PRESETS: readonly CodexPresetRow[] = [
  ["cc-kimi","Kimi","openai_responses","https://api.moonshot.cn/v1",["kimi-k3","kimi-k2.7-code"],"cn_official"],
  ["cc-kimi-global","Kimi Global","openai_responses","https://api.moonshot.ai/v1",["kimi-k3","kimi-k2.7-code"],"cn_official"],
  ["cc-kimi-coding","Kimi For Coding","openai_responses","https://api.kimi.com/coding/v1",["kimi-for-coding","kimi-for-coding-highspeed","k3","k3-256k"],"cn_official"],
  ["cc-kimi-coding-global","Kimi For Coding Global","openai_responses","https://api.kimi.ai/coding/v1",["kimi-for-coding","kimi-for-coding-highspeed","k3","k3-256k"],"cn_official"],
  ["cc-packycode","PackyCode","openai_responses","https://www.packyapi.ai/v1",["gpt-5.6-sol"],"third_party"],
  ["cc-zetaapi","ZetaAPI","openai_responses","https://api.zetaapi.ai/v1",["gpt-5.6-sol"],"aggregator"],
  ["cc-apinebula","APINebula","openai_responses","https://apinebula.ai/v1",["gpt-5.6-sol"],"third_party"],
  ["cc-aicodemirror","AICodeMirror","openai_responses","https://api.aicodemirror.ai/api/codex/backend-api/codex",["gpt-5.6-sol"],"third_party"],
  ["cc-patewayai","PatewayAI","openai_responses","https://api.pateway.ai/v1",["gpt-5.6-sol"],"third_party"],
  ["cc-fenno","FennoAI","openai_responses","https://api.fenno.ai",["gpt-5.6-sol"],"aggregator"],
  ["cc-runapi","RunAPI","openai_responses","https://runapi.host/v1",["gpt-5.6-sol"],"aggregator"],
  ["cc-shengsuanyun","Shengsuanyun","openai_responses","https://router.shengsuanyun.com/api/v1",["openai/gpt-5.6-sol"],"aggregator"],
  ["cc-aigocode","AIGoCode","openai_responses","https://api.aigocode.app",["gpt-5.6-sol"],"third_party"],
  ["cc-qiniu","Qiniu","openai_responses","https://api.qnaigc.com/bypass/openai/v1",["gpt-6-astra"],"aggregator"],
  ["cc-aicoding","AICoding","openai_responses","https://api.aicoding.inc",["gpt-5.6-sol"],"third_party"],
  ["cc-subrouter","SubRouter","openai_responses","https://subrouter.ai/v1",["gpt-5.6-sol"],"aggregator"],
  ["cc-fluxa-tokenplan","FluxA Token Plan","openai_chat","https://api.baiduqianfan.ai/v2/tokenplan/team",["deepseek-v4-pro","deepseek-v4-flash-0731","deepseek-v4-flash","deepseek-v3.2","glm-5.2","glm-5.1","glm-5","kimi-k2.6"],"aggregator"],
  ["cc-apikey-fun","APIKEY.FUN","openai_responses","https://api.apikey.fan/v1",["gpt-5.6-sol"],"third_party"],
  ["cc-9527code","9527CODE","openai_responses","https://9527.codes/v1",["gpt-5.6-sol"],"aggregator"],
  ["cc-code0","Code0","openai_responses","https://code0.ai/v1",["gpt-5.6-sol"],"aggregator"],
  ["cc-teamorouter","TeamoRouter","openai_responses","https://api.teamorouter.cn/v1",["gpt-5.6-sol"],"aggregator"],
  ["cc-ppio","PPIO","openai_chat","https://api.ppio.com/openai/v1",["deepseek/deepseek-v4-flash-0731"],"aggregator"],
  ["cc-claudecn","ClaudeCN","openai_responses","https://claudecn.top/v1",["gpt-5.6-sol"],"third_party"],
  ["cc-ark-agentplan","火山 Agent Plan","openai_responses","https://ark.cn-beijing.volces.com/api/plan/v3",["ark-code-latest"],"cn_official"],
  ["cc-ark-codingplan","火山 Coding Plan","openai_responses","https://ark.cn-beijing.volces.com/api/coding/v3",["ark-code-latest"],"cn_official"],
  ["cc-byteplus","BytePlus","openai_responses","https://ark.ap-southeast.bytepluses.com/api/coding/v3",["ark-code-latest"],"cn_official"],
  ["cc-doubaoseed","Volcengine Doubao","openai_responses","https://ark.cn-beijing.volces.com/api/v3",["doubao-seed-2-1-pro-260628"],"cn_official"],
  ["cc-siliconflow","SiliconFlow","openai_chat","https://api.siliconflow.cn/v1",["deepseek-ai/DeepSeek-V4-Flash"],"aggregator"],
  ["cc-siliconflow-en","SiliconFlow en","openai_chat","https://api.siliconflow.com/v1",["MiniMaxAI/MiniMax-M3"],"aggregator"],
  ["cc-a6api","A6API","openai_responses","https://api.a6api.com/v1",["gpt-5.6-sol"],"aggregator"],
  ["cc-compshare","Compshare","openai_responses","https://api.modelverse.cn/v1",["gpt-6-astra"],"aggregator"],
  ["cc-compshare-coding","Compshare Coding Plan","openai_responses","https://cp.compshare.cn/v1",["gpt-5.6-sol"],"aggregator"],
  ["cc-ccsub","CCSub","openai_responses","https://www.ccsub.net/v1",["gpt-6-astra"],"aggregator"],
  ["cc-sssaicode","SSSAiCode","openai_responses","https://node-hk.sssaicodeapi.com/api/v1",["gpt-5.6-sol"],"third_party"],
  ["cc-soleapi","SoleAPI","openai_responses","https://soleapi.com/v1",["gpt-5.6-sol"],"aggregator"],
  ["cc-micu","Micu","openai_responses","https://www.micuapi.ai/v1",["gpt-5.6-sol"],"third_party"],
  ["cc-rightcode","RightCode","openai_responses","https://www.rightapi.ai/codex/v1",["gpt-5.6-sol"],"third_party"],
  ["cc-etok","ETok.ai","openai_responses","https://api.etok.ai/v1",["gpt-5.6-sol"],"third_party"],
  ["cc-cubence","Cubence","openai_responses","https://api.cubence.com/v1",["gpt-5.6-sol"],"third_party"],
  ["cc-crazyrouter","CrazyRouter","openai_responses","https://cn.crazyrouter.com/v1",["gpt-5.6-sol"],"third_party"],
  ["cc-dmxapi","DMXAPI","openai_responses","https://www.dmxapi.cn/v1",["gpt-5.6-sol"],"aggregator"],
  ["cc-sudocode-chat","SudoCode.chat","openai_responses","https://api.sudocode.chat/v1",["gpt-5.6-sol"],"third_party"],
  ["cc-sudocode-us","SudoCode.us","openai_responses","https://sudocode.us/v1",["gpt-5.6-sol"],"third_party"],
  ["cc-xycai","XycAi","openai_responses","https://apicdn.xycai.us/v1",["gpt-5.6-sol"],"aggregator"],
  ["cc-amux","Amux","openai_responses","https://api.amux.ai/v1",["gpt-5.6-sol"],"aggregator"],
  ["cc-atlascloud","AtlasCloud","openai_chat","https://api.atlascloud.ai/v1",["zai-org/glm-5.2"],"aggregator"],
  ["cc-soshow","Soshow","openai_responses","https://maas.so-show.com/v1",["gpt-5.6-sol"],"aggregator"],
  ["cc-deepseek","DeepSeek","openai_responses","https://api.deepseek.com",["deepseek-flash","deepseek-v4-pro"],"cn_official"],
  ["cc-zhipu-glm","Zhipu GLM","openai_responses","https://open.bigmodel.cn/api/v1",["glm-5.3","glm-5-turbo"],"cn_official"],
  ["cc-zhipu-glm-en","Zhipu GLM en","openai_responses","https://api.z.ai/api/v1",["glm-5.3"],"cn_official"],
  ["cc-qianfan","Baidu Qianfan","openai_responses","https://qianfan.baidubce.com/v2",["deepseek-v4-pro","deepseek-v4-flash"],"cn_official"],
  ["cc-qianfan-coding","Baidu Qianfan Coding Plan","openai_chat","https://qianfan.baidubce.com/v2/coding",["qianfan-code-latest"],"cn_official"],
  ["cc-qianfan-tokenplan","Baidu Qianfan Token Plan","openai_chat","https://qianfan.baidubce.com/v2/tokenplan/personal",["deepseek-v4-pro","deepseek-v4-flash","deepseek-v4-flash-0731","glm-5.2","glm-5.1","kimi-k2.6"],"cn_official"],
  ["cc-qianwenai","千问AI平台","openai_responses","https://dashscope.aliyuncs.com/compatible-mode/v1",["qwen3.8-max","qwen3.8-2.4t-a95b","qwen3.8-27b"],"cn_official"],
  ["cc-qianwenai-token-plan","千问AI平台 Token Plan","openai_responses","https://token-plan.cn-beijing.maas.aliyuncs.com/compatible-mode/v1",["qwen3.8-max","qwen3.8-flash"],"cn_official"],
  ["cc-qwencloud","QwenCloud","openai_responses","https://dashscope-intl.aliyuncs.com/compatible-mode/v1",["qwen3.8-max","qwen3.8-flash","qwen3.7-max","qwen3.8-2.4t-a95b","qwen3.8-27b"],"cn_official"],
  ["cc-qwencloud-coding","QwenCloud For Coding","openai_chat","https://coding-intl.dashscope.aliyuncs.com/v1",["qwen3.7-plus","qwen3.6-plus","qwen3-coder-plus"],"cn_official"],
  ["cc-qwencloud-token-plan","QwenCloud Token Plan","openai_responses","https://token-plan.ap-southeast-1.maas.aliyuncs.com/compatible-mode/v1",["qwen3.8-max","qwen3.8-flash","qwen3.7-max"],"cn_official"],
  ["cc-hy3-tokenhub","Tencent Hunyuan","openai_responses","https://tokenhub.tencentmaas.com/v1",["hy3","hy4-preview","hy3-preview"],"cn_official"],
  ["cc-tencent-token-plan","Tencent Token Plan","openai_chat","https://api.lkeap.cloud.tencent.com/plan/v3",["tc-code-latest","deepseek-v4-flash-202605","deepseek-v4-pro-202606","minimax-m2.7","glm-5","glm-5.1","glm-5.2","hy3","hy3-preview"],"cn_official"],
  ["cc-tencent-token-plan-intl","Tencent Token Plan (Intl)","openai_chat","https://tokenhub-intl.tencentcloudmaas.com/plan/v3",["auto","glm-5.2","kimi-k2.6","deepseek-v4-pro-202606","deepseek-v4-flash-202605","minimax-m3"],"cn_official"],
  ["cc-tencent-token-plan-enterprise-pro","Tencent Token Plan Enterprise Pro","openai_chat","https://tokenhub.tencentmaas.com/plan/v3",["auto","glm-5.3","glm-5.2","glm-5","glm-5.1","glm-5-turbo","kimi-k2.7-code","kimi-k2.7-code-highspeed","kimi-k2.6","minimax-m2.7","minimax-m3","deepseek-v4-flash","deepseek-v4-pro","deepseek-v4-flash-0731","deepseek-v4-pro-0813","deepseek-v4-flash-202605","deepseek-v4-pro-202606"],"cn_official"],
  ["cc-tencent-token-plan-enterprise-pro-intl","Tencent Token Plan Enterprise Pro (Intl)","openai_chat","https://tokenhub-intl.tencentcloudmaas.com/plan/v3",["auto","glm-5.3","glm-5.2","minimax-m3","kimi-k2.7-code","kimi-k2.7-code-highspeed","deepseek-v4-flash","deepseek-v4-pro","deepseek-v4-flash-0731","deepseek-v4-pro-0813","deepseek-v4-flash-202605","deepseek-v4-pro-202606"],"cn_official"],
  ["cc-tencent-token-plan-enterprise-lite","Tencent Token Plan Enterprise Lite","openai_chat","https://tokenhub.tencentmaas.com/plan/v3",["auto"],"cn_official"],
  ["cc-tencent-token-plan-enterprise-lite-intl","Tencent Token Plan Enterprise Lite (Intl)","openai_chat","https://tokenhub-intl.tencentcloudmaas.com/plan/v3",["auto"],"cn_official"],
  ["cc-stepfun-api","StepFun API","openai_responses","https://api.stepfun.com/v1",["step-3.7-flash"],"cn_official"],
  ["cc-stepfun-api-en","StepFun API en","openai_responses","https://api.stepfun.ai/v1",["step-3.7-flash"],"cn_official"],
  ["cc-stepfun","StepFun","openai_chat","https://api.stepfun.com/step_plan/v1",["step-3.7-flash","step-3.5-flash-2603","step-3.5-flash"],"cn_official"],
  ["cc-stepfun-en","StepFun en","openai_chat","https://api.stepfun.ai/step_plan/v1",["step-3.7-flash","step-3.5-flash-2603","step-3.5-flash"],"cn_official"],
  ["cc-modelscope","ModelScope","openai_chat","https://api-inference.modelscope.cn/v1",["ZhipuAI/GLM-5.2"],"aggregator"],
  ["cc-longcat","Longcat","openai_responses","https://api.longcat.chat/openai/v1",["LongCat-2.0"],"cn_official"],
  ["cc-minimax","MiniMax","openai_responses","https://api.minimax.cn/v1",["MiniMax-M3"],"cn_official"],
  ["cc-minimax-en","MiniMax en","openai_responses","https://api.minimax.io/v1",["MiniMax-M3"],"cn_official"],
  ["cc-astron-coding-plan","Astron Coding Plan","openai_responses","https://maas-coding-api.cn-huabei-1.xf-yun.com/v1",["astron-code-latest"],"cn_official"],
  ["cc-bailing","BaiLing","openai_chat","https://api.ant-ling.com/v1",["Ling-2.6-1T"],"cn_official"],
  ["cc-xiaomi-mimo","Xiaomi MiMo","openai_responses","https://api.xiaomimimo.com/v1",["mimo-v2.6-pro","mimo-v2.6-flash","mimo-v2.6-pro-ultraspeed","mimo-v2.5-pro","mimo-v2.5"],"cn_official"],
  ["cc-xiaomi-mimo-token-plan","Xiaomi MiMo Token Plan (China)","openai_responses","https://token-plan-cn.xiaomimimo.com/v1",["mimo-v2.6-pro","mimo-v2.6-flash","mimo-v2.5-pro","mimo-v2.5"],"cn_official"],
  ["cc-novita","Novita AI","openai_chat","https://api.novita.ai/openai/v1",["zai-org/glm-5.3"],"aggregator"],
  ["cc-xai","xAI (Grok)","openai_responses","https://api.x.ai/v1",["grok-4.5","grok-4.7"],"third_party"],
  ["cc-nvidia","Nvidia","openai_chat","https://integrate.api.nvidia.com/v1",["moonshotai/kimi-k3"],"aggregator"],
  ["cc-opencode-go","OpenCode Go","openai_chat","https://opencode.ai/zen/go/v1",["glm-5.3","glm-5.3-flash","kimi-k3","deepseek-v4-pro","deepseek-v4-flash","mimo-v2.5-pro"],"third_party"],
  ["cc-aihubmix","AiHubMix","openai_responses","https://aihubmix.com/v1",["gpt-5.6-sol"],"aggregator"],
  ["cc-cherryin","CherryIN","openai_responses","https://open.cherryin.net/v1",["openai/gpt-5.6-sol"],"aggregator"],
  ["cc-relaxycode","RelaxyCode","openai_responses","https://www.relaxycode.com/v1",["gpt-5.6-sol"],"third_party"],
  ["cc-e-flowcode","E-FlowCode","openai_responses","https://e-flowcode.cc/v1",["gpt-5.6-sol"],"third_party"],
  ["cc-pipellm","PIPELLM","openai_responses","https://cc-api.pipellm.ai/v1",["gpt-5.6-sol"],"aggregator"],
  ["cc-openrouter","OpenRouter","openai_responses","https://openrouter.ai/api/v1",["gpt-5.6-sol"],"aggregator"],
  ["cc-therouter","TheRouter","openai_responses","https://api.therouter.ai/v1",["openai/gpt-5.3-codex"],"aggregator"],
  ["cc-jiekou","JieKou AI","openai_chat","https://api.jiekou.ai/openai/v1",["claude-fable-5"],"aggregator"],
  ["cc-aicodewith","AICodeWith","openai_responses","https://api.aicodewith.ai/v1",["gpt-5.6-sol"],"aggregator"],
];

